import Head from 'next/head'
import Navigation from "../component/Navigation"
import { Button } from '@mui/material'

export default function Home() {
  return (
    <div className="min-h-screen flex">
      <head>
        <title>GPA/CGPA Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300&display=swap" rel="stylesheet" />
      </head>
      <div className='m-auto px-5'>
        <Navigation nav={[]}/>
        <p className='text-3xl mb-5'> Select Regulation  </p>
        <Button className='mb-5 w-full text-lg' variant="contained" href="/R2013">
          R2013
        </Button> <br />
        <Button variant="contained" className='w-full text-lg' href="/R2017">
          R2017
        </Button>
      </div>
    </div>
  )
}
